baseURL = "/"
languageCode = "en-us"
title = "Liu - blog"
themesDir = "themes"
theme = "ananke"

SectionPagesMenu = "main"
DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
[languages]
  [languages.en]
    title = "liuliu's live blog"
    weight = 1
    contentDir = "content/en"
    #languageDirection = 'rtl' #for Right-To-Left languages
  [languages.cn]
    title = "liuliu's live blog"
    weight = 2
    contentDir = "content/cn"
[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30



[params]
  favicon = "my_icon.ico"
  google_analytics_id=""

  text_color = ""
  author = "liuliu"

  site_logo = ""
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/qwerttuuop66/"