baseURL = "/"
languageCode = "en-us"
title = "Hugo Whisper Theme"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Article"
    url = "/docs/"
    weight = 2
[[menu.main]]
    name = "Technique"
    url = "/docs/"
    weight = 3
[[menu.main]]
    name = "Movie"
    url = "/docs/"
    weight = 4
[[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 4
[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = "Let's start our journey"
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  # homepage_image = '/images/share.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = " Liuliu's live Blog is a platform to share good article,techniques, arts, films with you!"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
